import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Marquee from "@/components/Marquee";

const notoSerifBangla = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBangla.className} h-full antialiased`}
    >
      <body>
        <NavBar />
        <Marquee />
        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  );
}
